### ISSUE TITLE
Support portrait mode on iPad

### ISSUE THREAD

**Issue by raphpay** [jeyries/calculator#3]
We can't use the portrait mode on iPad, it could be great ! ( even without the granma :) )

**Comment by jeyries** [comment]
Well, the app was getting rejected by the App Store review team because of the portrait mode :
"Your app is too similar to native Calculator app, which creates a misleading association with Apple products."
Maybe if I could find a way to add the Grandma somewhere in the portrait mode, it could get accepted ...
